name: Build Multiple LKM
on:
  workflow_dispatch:

jobs:
  build-lkm:
    uses: ./.github/workflows/gki-kernel.yml
    with:
      version: android14-6.1
      version_name: android14-6.1.43
      tag: android14-6.1-2023-11
      os_patch_level: 2023-11
      module_dir: lkm
      module_name: lkm
      module_config: LKM_MOD
      build_lkm: true
  build-pvm:
    strategy:
      matrix:
        include:
          - version: android12-5.10
            sub_level: 209
            os_patch_level: 2024-05
          - version: android13-5.10
            sub_level: 209
            os_patch_level: 2024-05
          - version: android13-5.15
            sub_level: 148
            os_patch_level: 2024-05
          - version: android14-5.15
            sub_level: 148
            os_patch_level: 2024-05
          - version: android14-6.1
            sub_level: 75
            os_patch_level: 2024-05
          - version: android15-6.6
            sub_level: 30
            os_patch_level: 2024-07
    uses: ./.github/workflows/gki-kernel.yml
    with:
      version: ${{ matrix.version }}
      version_name: ${{ matrix.version }}.${{ matrix.sub_level }}
      tag: ${{ matrix.version }}-${{ matrix.os_patch_level }}
      module_dir: pvm
      module_name: pvm
      module_config: PVM_MOD
      build_lkm: true
